#!/usr/bin/env bash

log_file=~/.backup.log
echo view logs: tail -F $log_file
exec 1>>$log_file
exec 2>>$log_file

echo Started At: `Date`
echo ---------------------------------------------------------------------------------

# install applications
pushd ./install_apps 
./install
popd

# dock
pushd dock
./dock
./dock
popd

