#!/usr/bin/env bash

set -e

function install_dmg() {
	app=$1;
	app_dmg=$2;

	mount_output=`hdiutil mount "$app_dmg"`;

	app_folder=`echo $mount_output | grep -o /Volumes.*`;

	mount_point=`echo $mount_output | grep -o /dev/\[a-z0-9\]*`;
	mount_point=`echo $mount_point | cut -d' ' -f2`;

	cp -R "$app_folder"/*.app "$app";

	hdiutil unmount "$mount_point";
}

function install_zip() {
	app=$1;
	app_zip=$2;

	unzip "$app_zip" -d "$app.backup";
	mv "$app.backup"/* "$app";
	rm -fr "$app.backup";
}


function install_app() {
	url=$2;
	app_pkg="$download_folder/$1";
	app="$applications_folder/$1.app";
 	[ $force == true ] && rm -fr $app;
	if [ ! -d "$app" ]
	then
		echo - Installing \|$1\| FROM \|$url\|;

		curl -L "$url" > "$app_pkg";
		if [[ ! -z `file $app_pkg | grep -i -ioE \(bzip\|zlib\)` ]]; then package_type=dmg;
		elif [[ ! -z `file $app_pkg | grep -io zip` ]]; then package_type=zip;
		else package_type=unk;
		fi;

		if [ $package_type == 'dmg' ]; then install_dmg "$app" "$app_pkg";
		elif [ $package_type == 'zip' ]; then install_zip "$app" "$app_pkg";
		else echo "Unsupperted package type";
		fi;

		rm "$app_pkg"
	fi;
}

# vars
prefix=~/goinfre;
applications_folder="$prefix/Applications";
download_folder="$applications_folder/.downloads";
apps=./apps.txt;

mkdir -p $download_folder;

# main
force=false;
while getopts 'f' opt; do
	case $opt in
		f) force=true && break;;
		?) exit 0;;
	esac;
done

for req in `cat $apps`;
do
	app_name=`echo $req | cut -d\: -f1`;
	app_url=`echo $req | cut -d\: -f2-`;
	install_app "$app_name" "$app_url";
done
